version: 0.2

env:
    parameter-store:
        S3_BUCKET: "/ImageRecognition/ImageRecognitionArtifactStore"
phases:
  install:
    commands:
      - curl https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.200-linux-x64-binaries -o dotnet-sdk-6.tar.gz
      - mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.tar.gz -C $HOME/dotnet
      - export DOTNET_ROOT=$HOME/dotnet
      - export PATH=$HOME/dotnet:$PATH
      - apt-get update && apt-get install -y zip
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands:
      - cd ./Application/API/ImageRecognition.API
      - /root/.dotnet/tools/dotnet-lambda package-ci --serverless-template serverless.template --output-template updated.template --s3-bucket $S3_BUCKET
artifacts:
  files:
    - ./Application/API/ImageRecognition.API/updated.template
  discard-paths: yes
