version: 0.2

env:
    variables:
        DOTNET_SDK_URL: "https://download.visualstudio.microsoft.com/download/pr/807f9d72-4940-4b1a-aa4a-8dbb0f73f5d7/cb666c22a87bf9413f29615e0ba94500/dotnet-sdk-6.0.200-linux-x64.tar.gz"
    parameter-store:
        DOCKER_TAG: "/ImageRecognition/FrontendTag"
        DOCKER_REPO: "/ImageRecognition/FrontendRepository"
phases:
  install:
    commands:
      - curl $DOTNET_SDK_URL -o dotnet-sdk-6.tar.gz
      - mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-6.tar.gz -C $HOME/dotnet
      - export DOTNET_ROOT=$HOME/dotnet
      - export PATH=$HOME/dotnet:$PATH
      - apt-get update && apt-get install -y zip
      - dotnet tool install -g Amazon.ECS.Tools
  build:
    commands:
      - cd ./Application/UI/Blazor/ImageRecognition
      - /root/.dotnet/tools/dotnet-ecs push-image --config-file codebuild-defaults.json --tag $DOCKER_TAG
  post_build:
    commands:
      - printf '[{"name":"ImageRecognitionBlazerFrontend","imageUri":"%s"}]' $DOCKER_REPO > imagedefinitions.json
artifacts:
  files:
    - ./Application/UI/Blazor/ImageRecognition/imagedefinitions.json
  discard-paths: yes